-- Note: Standard Snowflake tables do not enforce key constraints. They are defined here for documentation purposes.

ALTER TABLE PROVIDER_DEMOGRAPHICS ADD PRIMARY KEY (RNDRNG_NPI);
ALTER TABLE PROVIDER_SERVICES ADD PRIMARY KEY (RNDRNG_NPI, HCPCS_CD);
ALTER TABLE HOSPITAL_GENERAL_INFORMATION ADD PRIMARY KEY (FACILITY_ID);
ALTER TABLE PROVIDER_HOSPITAL_AFFILIATION ADD PRIMARY KEY (NPI, FACILITY_AFFILIATIONS_CERTIFICATION_NUMBER);
ALTER TABLE MIPS_PERFORMANCE ADD PRIMARY KEY (NPI, ORG_PAC_ID);
ALTER TABLE MIPS_METRICS ADD PRIMARY KEY (NPI, MEASURE_CD);
ALTER TABLE HOSPITAL_COMPLICATIONS_DEATHS ADD PRIMARY KEY (FACILITY_ID, MEASURE_ID);
ALTER TABLE HOSPITAL_UNPLANNED_VISITS ADD PRIMARY KEY (FACILITY_ID, MEASURE_ID);
ALTER TABLE HOSPITAL_HAI ADD PRIMARY KEY (FACILITY_ID, MEASURE_ID);
ALTER TABLE HOSPITAL_HCAHPS ADD PRIMARY KEY (FACILITY_ID, HCAHPS_MEASURE_ID);
ALTER TABLE PROVIDER_SUMMARY ADD PRIMARY KEY (RNDRNG_NPI);
ALTER TABLE RUCA_ZIP_CODES ADD PRIMARY KEY (ZIPCODE);

ALTER TABLE PROVIDER_SERVICES ADD FOREIGN KEY (RNDRNG_NPI) REFERENCES PROVIDER_DEMOGRAPHICS(RNDRNG_NPI);
ALTER TABLE PROVIDER_HOSPITAL_AFFILIATION ADD FOREIGN KEY (NPI) REFERENCES PROVIDER_DEMOGRAPHICS(RNDRNG_NPI);
ALTER TABLE PROVIDER_HOSPITAL_AFFILIATION ADD FOREIGN KEY (FACILITY_AFFILIATIONS_CERTIFICATION_NUMBER) REFERENCES HOSPITAL_GENERAL_INFORMATION(FACILITY_ID);
ALTER TABLE MIPS_PERFORMANCE ADD FOREIGN KEY (NPI) REFERENCES PROVIDER_DEMOGRAPHICS(RNDRNG_NPI);
ALTER TABLE MIPS_METRICS ADD FOREIGN KEY (NPI) REFERENCES PROVIDER_DEMOGRAPHICS(RNDRNG_NPI);
ALTER TABLE HOSPITAL_COMPLICATIONS_DEATHS ADD FOREIGN KEY (FACILITY_ID) REFERENCES HOSPITAL_GENERAL_INFORMATION(FACILITY_ID);
ALTER TABLE HOSPITAL_UNPLANNED_VISITS ADD FOREIGN KEY (FACILITY_ID) REFERENCES HOSPITAL_GENERAL_INFORMATION(FACILITY_ID);
ALTER TABLE HOSPITAL_HAI ADD FOREIGN KEY (FACILITY_ID) REFERENCES HOSPITAL_GENERAL_INFORMATION(FACILITY_ID);
ALTER TABLE HOSPITAL_HCAHPS ADD FOREIGN KEY (FACILITY_ID) REFERENCES HOSPITAL_GENERAL_INFORMATION(FACILITY_ID);
ALTER TABLE PROVIDER_SUMMARY ADD FOREIGN KEY (RNDRNG_NPI) REFERENCES PROVIDER_DEMOGRAPHICS(RNDRNG_NPI);